- name: Create output directory on all hosts
  hosts: all
  tasks:
    - import_tasks: ansible/tasks/output_dir.yaml

- name: Install and configure LXD on the host.
  hosts: hypervisor
  become: true
  roles:
    - role: ansible/roles/lxd

- name: Deploy MAAS server
  hosts: hypervisor
  become: true
  roles:
    - role: ansible/roles/maas
      vars:
        maas_user: "{{ maas.user }}"
        maas_password: "{{ maas.password }}"

- name: Add MAAS client to localhost
  hosts: localhost
  tasks:
    - name: Install MAAS snap
      snap:
        name: maas
      become: true

    - name: Login to MAAS
      import_role:
        name: ansible/roles/maas
        tasks_from: login.yaml
      vars:
        maas_user: "{{ maas.user }}"
        maas_url: "{{hostvars[groups.hypervisor[0]]['maas_url']}}"
        maas_apikey: "{{hostvars[groups.hypervisor[0]]['maas_apikey']}}"

- name: Register LXD VM host on MAAS
  hosts: hypervisor
  tasks:
    - import_role:
        name: ansible/roles/maas
        tasks_from: add-lxd-vm-host.yaml
      vars:
        name: hypervisor
        maas_user: "{{ maas.user }}"
        lxd_address: "{{ maas_ip }}:8443"

- name: Configure the networks in MAAS
  hosts: localhost
  tasks:
    - name: "Configure network '{{ item.name }}' on MAAS"
      include_role:
        name: ansible/roles/maas
        tasks_from: configure-network.yaml
      vars:
        network: "{{ item }}"
      with_items: "{{ networks }}"

- name: Configure the Ubuntu images on MAAS
  hosts: localhost
  tasks:
    - include_role:
        name: ansible/roles/maas
        tasks_from: configure-boot-source-selections.yaml
      vars:
        release: "{{ item }}"
      with_items: "{{ ubuntu_series }}"

- name: Configure the MAAS cloud in Juju
  hosts: localhost
  tasks:
    - import_role:
        name: ansible/roles/juju
      vars:
        maas_user: "{{ maas.user }}"
        maas_apikey: "{{ maas_apikey }}"
        maas_url: "{{ maas_url }}"
        juju_cloud: "{{ env_name }}"
        juju_channel: "2.9/stable"

- name: Deploy OpenStack
  hosts: localhost
  roles:
    - role: ansible/roles/environments/openstack
      vars:
        maas_api_url: "{{ maas_url }}"
        maas_api_key: "{{ maas_apikey }}"
        maas_vm_host_id: "{{ vmhost.id }}"
        machines: "{{ vms }}"

- name: Deploy Landscape
  hosts: localhost
  roles:
    - role: ansible/roles/environments/landscape
      vars:
        model_series: jammy
        juju_cloud: "{{ env_name }}"
        admin_user: admin
        admin_password: password
