- name: Enable IPv4 forwarding.
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: true
    reload: true

- name: Install the LXD snap.
  snap:
    name: lxd

- name: Init LXD
  shell:
    cmd: |
      lxd init --auto

- name: Configure LXD access
  shell:
    cmd: |
      lxc config set core.https_address "[::]:8443"
      lxc config set core.trust_password "{{ trust_password }}"
