- name: Deploy Virsh VMs for MAAS
  hosts: localhost
  become: true
  vars_files:
  - variables.yaml

  tasks:
    - name: Install apt dependencies
      apt:
        pkg:
          - cloud-init
          - genisoimage
          - pkg-config
          - python3

    - name: Install snap dependencies
      snap:
        name:
          - lxd

    - name: Create work directory
      file:
        path: "{{ workdir }}"
        state: directory
        mode: "0755"

    - name: Create SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ workdir }}/id_rsa"
      register: maas_ssh_key

