config:
  core.https_address: "[::]:8443"
  core.trust_password: "{{trust_password}}"
storage_pools:
  - name: default
    driver: dir
networks:
  - name: lxdbr0
    config:
      ipv4.address: 10.10.10.1/24
      ipv4.dhcp: false
      ipv4.nat: true
      ipv6.address: none
      ipv6.dhcp: false
      ipv6.nat: true
      dns.mode: none
